### ISSUE TITLE
Add a html file for the project

### ISSUE THREAD

**Issue by dabbang123** [dabbang123/QR-Code-Generator.github.io#1]
# The file should be like this.
![screenshot](https://user-images.githubusercontent.com/73271173/136669256-b2104d51-f0c8-4426-85ae-7bec8b38958e.jpeg)

**Comment by sunidhisachan** [comment]
Hey @dabbang123 I can try  this.

**Comment by mr-vijaychauhan** [comment]
QR code App ! Please Check

![screencapture-127-0-0-1-5501-index-htm-2021-10-10-02_38_38](https://user-images.githubusercontent.com/63604585/136674035-0b88fd2c-5994-4183-a4c0-8140b1b6fc8f.png)
